import Foundation
import AppKit

/// Exports a GeneratedWorkflow in various formats.
/// Supports Markdown, AI agent prompt, GitHub Issue, and JSON.
struct WorkflowExporter {

    let workflow: GeneratedWorkflow
    let session: RecordingSession?

    // MARK: - Markdown Export

    /// Full Markdown document with steps, screenshots references, and metadata.
    func exportAsMarkdown() -> String {
        var md = "# \(workflow.title)\n\n"

        if !workflow.summary.isEmpty {
            md += "> \(workflow.summary)\n\n"
        }

        // Metadata
        if let session = session {
            md += "| Property | Value |\n|----------|-------|\n"
            md += "| Duration | \(formatDuration(session.duration)) |\n"
            md += "| Events | \(session.eventSummary.totalEvents) |\n"
            md += "| Frames | \(session.frames.count) |\n"
            md += "| Generated | \(formatDate(workflow.generatedAt)) |\n"
            md += "| Model | \(workflow.modelUsed) |\n\n"
        }

        md += "## Steps\n\n"

        for step in workflow.steps {
            md += "### \(step.stepNumber). \(step.title)\n\n"

            md += "**Action:** `\(step.actionType.rawValue)`"
            if let ui = step.uiElement {
                md += "  •  **Element:** \(ui)"
            }
            md += "\n\n"

            if step.description != step.title {
                md += "\(step.description)\n\n"
            }

            if let screenshot = step.screenshotFile {
                md += "![Step \(step.stepNumber)](\(screenshot))\n\n"
            }
        }

        // Transcript
        if let transcript = session?.transcript, !transcript.fullText.isEmpty {
            md += "## Transcript\n\n"
            md += "\(transcript.fullText)\n\n"
        }

        return md
    }

    // MARK: - AI Agent Prompt Export

    /// Standalone AI agent prompt (for Cursor, Codex, Copilot, etc.)
    func exportAsAIPrompt() -> String {
        guard let prompt = workflow.aiAgentPrompt, !prompt.isEmpty else {
            // Generate a basic prompt from steps
            return generateBasicPrompt()
        }
        return prompt
    }

    private func generateBasicPrompt() -> String {
        var prompt = "# Task: \(workflow.title)\n\n"
        prompt += "\(workflow.summary)\n\n"
        prompt += "## Steps to implement:\n\n"

        for step in workflow.steps {
            prompt += "\(step.stepNumber). [\(step.actionType.rawValue)] \(step.title)\n"
            if step.description != step.title {
                prompt += "   \(step.description)\n"
            }
        }

        return prompt
    }

    // MARK: - GitHub Issue Export

    /// Formatted as a GitHub Issue body with task list.
    func exportAsGitHubIssue() -> String {
        var body = "## Description\n\n"
        body += "\(workflow.summary)\n\n"

        body += "## Steps to Reproduce\n\n"

        for step in workflow.steps {
            body += "- [ ] **Step \(step.stepNumber):** \(step.title)\n"
            if step.description != step.title {
                body += "  \(step.description)\n"
            }
        }

        body += "\n## Additional Context\n\n"

        if let session = session {
            body += "- Recording duration: \(formatDuration(session.duration))\n"
            body += "- Total interactions: \(session.eventSummary.totalEvents)\n"
            body += "- Mouse clicks: \(session.eventSummary.mouseClicks)\n"
            body += "- Keystrokes: \(session.eventSummary.keystrokes)\n"
        }

        body += "- Generated by VibeTrace with \(workflow.modelUsed)\n"

        return body
    }

    // MARK: - JSON Export

    /// Full JSON export (workflow + session metadata).
    func exportAsJSON() -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601

        guard let data = try? encoder.encode(workflow) else {
            return "{\"error\": \"Failed to encode workflow\"}"
        }

        return String(data: data, encoding: .utf8) ?? "{}"
    }

    // MARK: - Clipboard

    /// Copy a specific format to the clipboard.
    static func copyToClipboard(_ text: String) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
    }

    // MARK: - Save to File

    /// Save export to a file and return the URL.
    func saveToFile(format: ExportFormat, directory: URL, baseName: String) throws -> URL {
        let content: String
        let ext: String

        switch format {
        case .markdown:
            content = exportAsMarkdown()
            ext = "md"
        case .aiPrompt:
            content = exportAsAIPrompt()
            ext = "txt"
        case .githubIssue:
            content = exportAsGitHubIssue()
            ext = "md"
        case .json:
            content = exportAsJSON()
            ext = "json"
        }

        let filename = "\(baseName)_\(format.rawValue).\(ext)"
        let url = directory.appendingPathComponent(filename)
        try content.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - Formats

    enum ExportFormat: String, CaseIterable, Identifiable {
        case markdown = "steps"
        case aiPrompt = "ai_prompt"
        case githubIssue = "github_issue"
        case json = "workflow"

        var id: String { rawValue }

        var displayName: String {
            switch self {
            case .markdown: return "Markdown Steps"
            case .aiPrompt: return "AI Agent Prompt"
            case .githubIssue: return "GitHub Issue"
            case .json: return "JSON Workflow"
            }
        }

        var icon: String {
            switch self {
            case .markdown: return "doc.richtext"
            case .aiPrompt: return "terminal"
            case .githubIssue: return "exclamationmark.circle"
            case .json: return "curlybraces"
            }
        }
    }

    // MARK: - Formatting

    private func formatDuration(_ seconds: TimeInterval) -> String {
        let mins = Int(seconds) / 60
        let secs = Int(seconds) % 60
        if mins > 0 { return "\(mins)m \(secs)s" }
        return "\(secs)s"
    }

    private func formatDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter.string(from: date)
    }
}
